# These are supported funding model platforms
github: chriseugenerodriguez
custom: ['https://www.buymeacoffee.com/7a6iTxbO23', 'https://paypal.me/crodr', 'https://buy.stripe.com/00g15d3thapybleeUU', 'https://buy.stripe.com/00g15d3thapybleeUU']
